// src/theme.ts
export const lightTheme = {
  mode: "light",
  body: "#FFFFFF",
  text: "#000000",
  toggleBorder: "#FFF",
  background: "#FFF",
  card: "#F9F9F9",
  border: "#eee",
  loaderBackground: "linear-gradient(#050a30, #d4f1f4, #050a30)",
  loaderColor: "black",
  buttonBackground: "#EBD9B4",
  headerBackground: "#F9EFDB",
  adviserTextBackground: "#F9EFDB",
  userTextBackground: "",
  notebookBackground: "beige",
  menuBackground: "#F9EFDB",
  animatedBackground: "#FFF",
  animatedBackgroundText: "#000",
};

export const darkTheme = {
  mode: "dark",
  body: "#363537",
  text: "#FAFAFA",
  toggleBorder: "#6B8096",
  background: "#000",
  card: "#2D2D2D",
  border: "black",
  loaderBackground: "linear-gradient(black, red, black)",
  loaderColor: "#FFFFFF",
  buttonBackground: "#3D3B40",
  headerBackground: "#202020",
  adviserTextBackground: "#000",
  userTextBackground: "",
  notebookBackground: "black",
  menuBackground: "#202020",
  animatedBackground: "#000",
  animatedBackgroundText: "#FFF",
};
